# Guess The Number
# Write a programme where the computer randomly generates a number between 0 and 20. 
# The user needs to guess what the number is. 
# If the user guesses wrong, tell them their guess is either too high, or too low. 
# This will get you started with the random library if you haven't already used it.
# Source: https://www.codementor.io/@ilyaas97/6-python-projects-for-beginners-yn3va03fs

import random
upper_range = 40
random_number = int(random.random() * upper_range)

user_guess = None
attempts = 0
total_attempts = 5

print("Please guess a number between 0 - {}".format(upper_range))
while user_guess != random_number:
    # Counter for max attempts
    if attempts == total_attempts:
        print("Random number generated by system {}".format(random_number))
        break
    else:
        attempts = attempts +1

    # Ask for a user input
    user_guess = input("{}. Please enter a number: ".format(attempts))

    try:
        user_guess = int(user_guess)
    except ValueError:
        print("Invalid input. Please only enter a number between 0 - {}".format(upper_range))
        continue

    # Validation
    if user_guess > upper_range:
        print("Your guess should be less than {}".format(upper_range))
    elif user_guess < 0:
        print("Your guess should be more than 0")

    # Business Logic
    # If the user guesses wrong, tell them their guess is either too high, or too low. 
    if user_guess > random_number:
        print("Your guess is more than system generated number. Think a lower number")
    elif user_guess < random_number:
        print("Your guess is less than system generated number. Think a bigger number")

else:
    # This block is executed if User authenticates before running out of attempts
    print("You guessed it right")